language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

before_install:
  - composer require --dev --no-update twig/twig:$TWIG_VERSION

install:
  - composer install

script:
  - ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.1
      env: TWIG_VERSION=1.x
    - php: 7.1
      env: TWIG_VERSION=2.x
    - php: 7.2
      env: TWIG_VERSION=1.x
    - php: 7.2
      env: TWIG_VERSION=2.x
    - php: 7.3
      env: TWIG_VERSION=1.x
    - php: 7.3
      env: TWIG_VERSION=2.x
  fast_finish: true
