name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    fail-fast: true

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-20.04"

        strategy:
            matrix:
                php-version:
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"
                    - "8.1"
                twig-version:
                    - "1.x"
                    - "2.x"
                    - "3.x"
                nicebooks-version:
                    - "0.2.x"
                include:
                  - php-version: "7.4"
                    twig-version: "1.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "7.4"
                    twig-version: "2.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "7.4"
                    twig-version: "3.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.0"
                    twig-version: "1.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.0"
                    twig-version: "2.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.0"
                    twig-version: "3.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.1"
                    twig-version: "1.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.1"
                    twig-version: "2.x"
                    nicebooks-version: "0.3.x"
                  - php-version: "8.1"
                    twig-version: "3.x"
                    nicebooks-version: "0.3.x"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  # Use composer.json for key, if composer.lock is not committed.
                  # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: |
                  composer config minimum-stability dev
                  composer require --dev --no-update twig/twig:${{ matrix.twig-version }} nicebooks/isbn:${{ matrix.nicebooks-version }}
                  composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Tests
              run: php vendor/bin/phpunit --coverage-text
