name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    fail-fast: true

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-22.04"

        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.1"
                    - "8.2"
                twig-version:
                    - "^2.15"
                    - "^3.5"
                nicebooks-version:
                    - "^0.3"
                    - "^0.4"
                exclude:
                  - php-version: "7.4"
                    nicebooks-version: "^0.4"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  # Use composer.json for key, if composer.lock is not committed.
                  # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: |
                  composer require --no-update "twig/twig:${{ matrix.twig-version }}" "nicebooks/isbn:${{ matrix.nicebooks-version }}"
                  composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Tests
              run: php vendor/bin/phpunit --coverage-text
